modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="adastraextra"
version="1.2.2"
displayName="Ad Astra Extra"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/ad-astra-extra"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Bullfighter"

[[dependencies.adastraextra]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.adastraextra]]
    modId="ad_astra"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.adastraextra]]
    modId="adastra"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

